### ISSUE TITLE
Examples don't work for Wemos D1 Mini (ESP8266) 

### ISSUE THREAD

**Issue by alastaira** [fredilarsen/ModuleInterface#15]
Blink example causes ESP8266 board to enter an infinite reset loop caused by memory allocation error. 
This appears to be due to use of strlen to access a PROGMEM char array, addressed in PR #14

**Comment by fredilarsen** [comment]
Pull request approved and merged.
Thank you for finding and fixing this bug. Seems I have been using Arduinos too much for my own project to find this.
