### ISSUE TITLE
ModuleInterface without master

### ISSUE THREAD

**Issue by mauricebauer** [fredilarsen/ModuleInterface#8]
Hello,
my first impression of ModuleInterface is: it is pretty solid and looks great. 
The question: Is it possible to get ModuleInterface without a central master getting to work? So I only want Modules (maybe "MultiMasters") which can communicate with each other with their inputs and outputs without a central master.
Example:
Two modules as light switches with the output "light:b1" and one relay module with has the corresponding input "light:b1" and reacts on those values.

At the moment I think this does not work without a master, maybe because of the heartbeats? (I havent read through the code...)

I think this implementation without master could fulfill a lot of home bus needs... (KNX for example is also without a central master)...

Thanks in advance for your work and your answer
Maurice

**Comment by fredilarsen** [comment]
Interesting angle. I suppose modules could get support to broadcast their outputs and pick up inputs from broadcasts from other modules.

But for this simple case you could simply let the relay module be a master for the switches? You can have multiple masters.

**Comment by fredilarsen** [comment]
Just a comment related to the master, it polls for the outputs of each module regularly, to make it robust to  potential lost packets, because the values will get there eventually.

But for a light swich you will probably mark the output change as an event to have it transferred immediately out-of-schedule in addition to the scheduled transfer.

**Comment by mauricebauer** [comment]
Okay, do you think ModuleInterface is the right protocol to Go with for this scenario? Or should I consider another protocol using PJON? Because it looks to me like ModuleInterface is Not designed for such an application?

**Comment by fredilarsen** [comment]
Only some switches that control a relay module? With no web page, database or configuration?

That is very simple, but the relay being a master and the switches sending the wanted relay state as an output flagged as an event, I think that should work fine and be possible with very little coding. 
What kind of devices and PJON strategy are you using?
